### ISSUE TITLE
CTX for ITS data?

### ISSUE THREAD

**Issue by hotblast** [biocore/redbiom#101]
I searched "redbiom summarize contexts".  It looks like all CTX (total 79) are for 16s study, none for ITS.  Can anyone make a CTX based on ITS amplicon study?
Thanks,
Gary

ContextName   SamplesWithData FeaturesWithData Description
--
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V4-41ebc6   100 14434 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Split libraries
Deblur-Illumina-16S-V4-250nt-3b87d8   200 14911 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Trimming (length: 250)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V6-8-150nt-bd7d4d   51 4250 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 150)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V9-150nt-bd7d4d   263 5054 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 150)
Deblur-Illumina-16S-V4-200nt-05cde0   7009 73599 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Trimming (length: 200)
Pick_closed-reference_OTUs-Greengenes-LS454-16S-V3-41ebc6   11760 35159 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Split libraries
Deblur-Illumina-16S-V4-100nt-fbc5b2   179406 6297806 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Trimming (length: 100)
Deblur-Illumina-16S-V3-90nt-99d1d8   1130 36905 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Trimming (length: 90)
Deblur-Illumina-16S-V3-150nt-780653   1139 9418 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Trimming (length: 150)
Pick_closed-reference_OTUs-Greengenes-IonTorrent-16S-V3-150nt-bd7d4d   32 1008 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 150)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V9-58196d   209 2633 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Deblur (Reference phylogeny for   SEPP: Greengenes_13.8)
Pick_closed-reference_OTUs-SILVA-LS454-16S-V3-150nt-96e6a9   3357 10563 Pick closed-reference OTUs (reference-seq:   \|projects\|qiita_data\|reference\|silva_119_Silva_119_rep_set97.fna) \| Trimming   (length: 150)
Pick_closed-reference_OTUs-Greengenes-LS454-16S-V4-41ebc6   7385 27273 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Split libraries
Pick_closed-reference_OTUs-Greengenes-LS454-16S-V6-100nt-a243a1   221 7294 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 100)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V4-90nt-44feac   173749 74298 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 90)
Pick_closed-reference_OTUs-Greengenes-IonTorrent-16S-V3-41ebc6   32 1433 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Split libraries
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V4-150nt-bd7d4d   145308 73089 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 150)
Deblur-Illumina-16S-V4-e40b83   1785 120797 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Split libraries FASTQ
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V9-100nt-a243a1   321 14922 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 100)
Pick_closed-reference_OTUs-SILVA-LS454-16S-V4-100nt-cb8fea   6067 9921 Pick closed-reference OTUs (reference-seq:   \|projects\|qiita_data\|reference\|silva_119_Silva_119_rep_set97.fna) \| Trimming   (length: 100)
Deblur-Illumina-16S-V6-8-150nt-780653   51 3906 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Trimming (length: 150)
Deblur-Illumina-16S-V3-100nt-fbc5b2   1130 42073 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Trimming (length: 100)
Deblur-Illumina-16S-V3-V4-150nt-780653   60 869 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Trimming (length: 150)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V34-5c6506   72 2221 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Split libraries FASTQ
Deblur-Illumina-16S-V3-e40b83   138 7273 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Split libraries FASTQ
Pick_closed-reference_OTUs-SILVA-LS454-16S-V4-150nt-96e6a9   6067 10792 Pick closed-reference OTUs (reference-seq:   \|projects\|qiita_data\|reference\|silva_119_Silva_119_rep_set97.fna) \| Trimming   (length: 150)
Deblur-Illumina-16S-V9-90nt-99d1d8   319 35817 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Trimming (length: 90)
Pick_closed-reference_OTUs-Greengenes-FASTA-16S-V3-100nt-a243a1   18 1706 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 100)
Deblur-Illumina-16S-V4-90nt-99d1d8   171936 4937125 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Trimming (length: 90)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V4-250nt-66a626   174 2686 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 250)
Pick_closed-reference_OTUs-SILVA-LS454-16S-V3-34e809   3288 6500 Pick closed-reference OTUs (reference-seq:   \|projects\|qiita_data\|reference\|silva_119_Silva_119_rep_set97.fna) \| Split   libraries
Pick_closed-reference_OTUs-SILVA-LS454-16S-V4-90nt-efd9ba   6067 8982 Pick closed-reference OTUs (reference-seq:   \|projects\|qiita_data\|reference\|silva_119_Silva_119_rep_set97.fna) \| Trimming   (length: 90)
Pick_closed-reference_OTUs-SILVA-LS454-16S-V3-100nt-cb8fea   3358 8501 Pick closed-reference OTUs (reference-seq:   \|projects\|qiita_data\|reference\|silva_119_Silva_119_rep_set97.fna) \| Trimming   (length: 100)
Deblur-Illumina-16S-V6-8-100nt-fbc5b2   51 2062 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Trimming (length: 100)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V4-5c6506   200552 84164 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Split libraries FASTQ
Pick_closed-reference_OTUs-Greengenes-LS454-16S-V6-150nt-bd7d4d   221 7227 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 150)
Pick_closed-reference_OTUs-SILVA-Illumina-16S-V4-90nt-efd9ba   942 7730 Pick closed-reference OTUs (reference-seq:   \|projects\|qiita_data\|reference\|silva_119_Silva_119_rep_set97.fna) \| Trimming   (length: 90)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V3-5c6506   1366 18170 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Split libraries FASTQ
Pick_closed-reference_OTUs-Greengenes-LS454-16S-V5-V7-90nt-44feac   84 4246 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 90)
Pick_closed-reference_OTUs-SILVA-LS454-16S-V4-34e809   6007 12821 Pick closed-reference OTUs (reference-seq:   \|projects\|qiita_data\|reference\|silva_119_Silva_119_rep_set97.fna) \| Split   libraries
Deblur-Illumina-16S-V34-150nt-780653   72 7819 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Trimming (length: 150)
Pick_closed-reference_OTUs-Greengenes-LS454-16S-V5-V7-41ebc6   84 1697 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Split libraries
Deblur-Illumina-16S-V9-100nt-fbc5b2   319 36485 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Trimming (length: 100)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V3-90nt-44feac   1135 14850 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 90)
Pick_closed-reference_OTUs-SILVA-Illumina-16S-V4-150nt-96e6a9   1306 41654 Pick closed-reference OTUs (reference-seq:   \|projects\|qiita_data\|reference\|silva_119_Silva_119_rep_set97.fna) \| Trimming   (length: 150)
Pick_closed-reference_OTUs-Greengenes-LS454-16S-V6-41ebc6   221 8193 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Split libraries
Pick_closed-reference_OTUs-Greengenes-IonTorrent-16S-V3-100nt-a243a1   32 1089 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 100)
Pick_closed-reference_OTUs-SILVA-Illumina-16S-V3-54d83f   138 1014 Pick closed-reference OTUs (reference-seq:   \|projects\|qiita_data\|reference\|silva_119_Silva_119_rep_set97.fna) \| Split   libraries FASTQ
Deblur-Illumina-16S-V9-150nt-780653   319 266737 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Trimming (length: 150)
Deblur-Illumina-16S-V4-125nt-3aae8b   25607 747030 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Trimming (length: 125)
Pick_closed-reference_OTUs-Greengenes-not   provided-16S-V4-150nt-bd7d4d 1905 10232 Pick closed-reference OTUs   (reference-seq: \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length:   150)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V3-150nt-bd7d4d   1156 6942 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 150)
Pick_closed-reference_OTUs-Greengenes-LS454-16S-V3-150nt-bd7d4d   11665 35776 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 150)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V6-8-100nt-a243a1   51 4586 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 100)
Pick_closed-reference_OTUs-SILVA-Illumina-16S-V4-54d83f   1585 22836 Pick closed-reference OTUs (reference-seq:   \|projects\|qiita_data\|reference\|silva_119_Silva_119_rep_set97.fna) \| Split   libraries FASTQ
Deblur-Illumina-16S-V4-150nt-780653   139516 7645682 Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM:   reference-hit.biom) \| Trimming (length: 150)
Pick_closed-reference_OTUs-Greengenes-not   provided-16S-V4-5c6506 1905 10244 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Split libraries FASTQ
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V4-200nt-a5e305   7009 16070 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 200)
Pick_closed-reference_OTUs-Greengenes-LS454-16S-V3-100nt-a243a1   11908 36166 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 100)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V9-90nt-44feac   321 11964 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 90)
Pick_closed-reference_OTUs-Greengenes-LS454-16S-V4-150nt-bd7d4d   7544 30847 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 150)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V3-100nt-a243a1   1135 16186 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 100)
Pick_closed-reference_OTUs-SILVA-Illumina-16S-V4-d1cf1d   20 5361 Pick closed-reference OTUs (reference-seq:   \|projects\|qiita_test_data\|reference\|Greengenes_13_8_gg_13_8-97_otus.fasta) \|   Split libraries FASTQ
Pick_closed-reference_OTUs-Greengenes-LS454-16S-V3-90nt-44feac   11899 34392 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 90)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V9-5c6506   388 5155 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Split libraries FASTQ
Pick_closed-reference_OTUs-SILVA-LS454-16S-V3-90nt-efd9ba   3358 7991 Pick closed-reference OTUs (reference-seq:   \|projects\|qiita_data\|reference\|silva_119_Silva_119_rep_set97.fna) \| Trimming   (length: 90)
Pick_closed-reference_OTUs-Greengenes-IonTorrent-16S-V3-90nt-44feac   32 1065 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 90)
Pick_closed-reference_OTUs-Greengenes-LS454-16S-V4-100nt-a243a1   7493 29896 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 100)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V34-150nt-bd7d4d   72 2653 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 150)
Pick_closed-reference_OTUs-Greengenes-LS454-16S-V5-V7-100nt-a243a1   84 4576 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 100)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V4-100nt-a243a1   173809 75990 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 100)
Pick_closed-reference_OTUs-Greengenes-FASTA-16S-V3-90nt-44feac   18 1682 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 90)
Pick_closed-reference_OTUs-Greengenes-FASTA-16S-V3-150nt-bd7d4d   18 1705 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 150)
Pick_closed-reference_OTUs-Greengenes-FASTA-16S-V3-5c6506   18 1741 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Split libraries FASTQ
Pick_closed-reference_OTUs-Greengenes-LS454-16S-V4-90nt-44feac   7505 27838 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 90)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V4-58196d   8468 34789 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Deblur (Reference phylogeny for   SEPP: Greengenes_13.8)
Pick_closed-reference_OTUs-Greengenes-LS454-16S-V5-V7-150nt-bd7d4d   84 4971 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 150)
Pick_closed-reference_OTUs-Greengenes-Illumina-16S-V4-125nt-65468f   27100 43261 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 125)
Pick_closed-reference_OTUs-Greengenes-LS454-16S-V6-90nt-44feac   221 6572 Pick closed-reference OTUs (reference-seq:   \|databases\|gg\|13_8\|rep_set\|97_otus.fasta) \| Trimming (length: 90)

**Comment by wasade** [comment]
See #102
