### ISSUE TITLE
How to get ITS amplicon environmental samples

### ISSUE THREAD

**Issue by hotblast** [biocore/redbiom#102]
My goal is to get the community profile of all ITS studies that have GPS location. I searched "redbiom search metadata ITS | redbiom summarize samples --category sample_type  | head".  All i got is 48 control blank.

Then I searched the https://qiita.ucsd.edu/study/list/ site , Among 543 entries in Qiita Public Studies, there are 19 studies having ITS in the Preparation Data Types field.

    After I got these 19 qiita_study_id, I was trying to get their sample data in BIOM file.  I used the following command. 

 redbiom search metadata "where qiita_study_id == 2020" | redbiom fetch samples --context $CTX --output study.biom

As I expected, I didn't get anything back, since I don't have CTX for ITS.
    Any suggestions on this?

**Comment by hotblast** [comment]
Updated: redbiom is only indexing 16S; thus, I can not find actual ITS samples using Redbox search.

**Comment by wasade** [comment]
That's correct, at the moment we're only indexing 16S. The preparation information for ITS and 18S is not nearly as uniform right now, so the contexts are not well defined.
