### ISSUE TITLE
Code inversion for ambiguities solving in fetch?

### ISSUE THREAD

**Issue by cotillau** [biocore/redbiom#108]
In functions fetch_samples_from_obserations and fetch_samples_from_samples, there may be an inversion in the [code](https://github.com/biocore/redbiom/blob/58b81c59422b3a7ba2da5ef580ad4b43805e205a/redbiom/commands/fetch.py#L157-160) when resolving ambiguities.

```
    if resolve_ambiguities == 'merge':
        tab = redbiom.fetch._ambiguity_keep_most_reads(tab, map_)
    elif resolve_ambiguities == 'most-reads':
        tab = redbiom.fetch._ambiguity_merge(tab, map_)
```

**Comment by wasade** [comment]
Can confirm -- good spot, thank you!
