### ISSUE TITLE
Bug in Querying for public microbiome data in Qiita using redbiom tutorial

### ISSUE THREAD

**Issue by AlohaPropolis** [biocore/redbiom#109]
When selecting the copy button and then pasting to the command line there is an error "command not found".
If the same command is selected (highlighted) using the the keyboard and then pasted to the terminal command prompt it works fine.

 $ cat > features << END
> TACGTAGGTGGCGAGCGTTGTCCGGATTTACTGGGTGTAAAGGGTGCGTAGGCGGATTGGCAAGTCAGAAGTGAAATCCATGGGCTTAACCCATGAACTGCTTTCAAAACTGTTTTTCTTGAGTAGTGCAGAGGTAGGCGGAATTCCCGG
> TACGTATGGTGCAAGCGTTATCCGGATTTACTGGGTGTAAGGGAGCGCAGGCGGTCTGGCAAGTCTGATGTGAAATACCGGGGCTTAACCCCGGAGCTGCATCCAAAACTGTAGTTCTTGAGTGGAGTAGAGGTAAGCGGAATTCCGAGT
> TACAGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCGCGTAGGTGGTTTGTTAAGTTGGAAGTGAAATCTATGGGCTTAACCCATAAACTGCTTTCAAAACTGCTGGTCTTGAGTGATGGAGAGGCAGGCGGAATTCCGTG
> TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGGCGGTAAGACAAGTCAGAAGTGAAAACCCAGGGCTTAACTCTGGGACTGCTTTTGAAACTGTCAGACTGGAGTGCAGGAGAGGTAAGCGGAATTCCTAG
> TACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTGTAAAGGGTGCGTAGACGGGAGAACAAGTTAGTTGTGAAATACCTCGGCTCAACTGAGGAACTGCAACTAAAACTGTACTTCTTGAGTGCAGGAGAGGTAAGTGGAATTACTAG
> TACGTAGGTGACAAGCGTTGTCCGGATTTACTGGGTGTAAAGGGCGCGTAGGCGGGATAGCAAGTCAGTCGTGAAATACCGGAGCTCAACTCCGGGGCTGCGATTGAAACTGTTATTCTTGAGTATCGGAGAGGAAAGCGGAATTCCTGG
> TACGTAGGGGGCAAGCGTTATCCGGAATTACTGGGTGTAAAGGGAGCGTAGACGGTGATGTAAGTCTGATGTGAAAGCCTCCGGCTCAACCGGAGAATTGCATCAGAAACTGTTGAACTTGAGTGCAGAAGAGGAGAGTGGAACTCTATG
> TACGTAGGTGGCAAGCGTTGTCCGGATTTACTGGGTGTAAGGGCGTGTAGCCGGGAAGGCAAGTCAGATGTGAAATCCATGGGCTCAACCTCCAGCCTGCATTTGAAACTGTAGTTCTTGAGTGTCGGAGAGGCAATCGGAATTCCGTGT
> TACGTAGGTGGCAAGCGTTGTCCGGATTTACTGGGTGTAAAGGGCGTGCAGCCGGGCTGACAAGTCAGATGTGAAATCCCGAGGCTTAACCTCGGAACTGCATTTGAAACTGTTAGTCTTGAGTATCGGAGAGGTCATCGGAATTCCTTG
> TACGTAGGTGGCGAGCGTTATCCGGAATTATTGGGCGTAAAGGGAGCGTAGACGGCTGTGCAAGTCTGAAGTGAAAGCCCGGGGCTCAACCCCGGGACTGCTTTGGAAACTGTGCAGCTAGAGTGTCGGAGAGGTAAGCGGAATTCCTAG
> END
-bash: $: command not found

Hope this help

Thanks

**Comment by wasade** [comment]
Thank you! Would it be possible to open this issue on the Qiita [issue tracker](https://github.com/qiita-spots/qiita)?
