### ISSUE TITLE
metadata search by study id not working

### ISSUE THREAD

**Issue by nvpatin** [biocore/redbiom#124]
I'm interested in downloading a subset of samples from the EMP (Study ID 13114). I installed the redbiom CLI using conda and set the server host to QIITA ('export REDBIOM_HOST=http://qiita.ucsd.edu:7329'). 

I can search samples by certain metadata fields (e.g. 'redbiom search metadata saline' works fine) but when I try 'redbiom search metadata "where qiita_study_id == 13114" I get a list of Traceback errors ending with "NameError: name 'Constant' is not defined" 

Separately, when I try "where empo_4 == "Water (saline)"" I get the error "(zsh: number expected)." Are there number codes for the empo_4 environment type?

**Comment by wasade** [comment]
Hi @nvpatin, could you tell me what version of redbiom is being used, and what version of python? The following should do it:

```bash
$ redbiom --version
$ python --version
```

**Comment by nvpatin** [comment]
redbiom version is 0.3.5
Python version is 3.11.0

**Comment by wasade** [comment]
Thanks! The latest version of redbiom is [0.3.9](https://github.com/biocore/redbiom/releases/tag/0.3.9) which should address this. Would it be possible to uninstall from `conda`, and `pip install redbiom`? I don't know why at the moment, but it looks like the conda builds are not indexing the latest version -- I'll need to examine the conda-forge recipe:

```bash
$ conda search -c conda-forge redbiom
Loading channels: done
# Name                       Version           Build  Channel             
redbiom                        0.3.4    pyh5ca1d4c_0  conda-forge         
redbiom                        0.3.5    pyh5ca1d4c_0  conda-forge
```

**Comment by nvpatin** [comment]
Thanks @wasade that fixed the problem! Appreciate the quick response.
