### ISSUE TITLE
should some of the output be optional in redbiom.fetch.data_from_samples

### ISSUE THREAD

**Issue by antgonza** [biocore/redbiom#70]
Not sure how expensive it actually is but I would suspect that is not "free" to always generate the biom and the dict; thus, should this method have 2 other counterparts that only return the biom or the dict?

**Comment by wasade** [comment]
Ambiguities are necessary to resolve before constructing the `Table` object, so it is for free.

**Comment by antgonza** [comment]
Right but constructing the Table actually takes resources (memory and time) so the point of this is to make the creation of the biom optional ...

**Comment by wasade** [comment]
I'm not aware of any consumer method that uses the ambiguity mapping, so I still don't understand the motivation. 

It is almost certainly the case that the HTTP requests and responses are the bulk of the time particularly as we're loading already sparse data through optimized mechanisms, although I'd be curious to see profiling results if you have them.

**Comment by antgonza** [comment]
We do this in Qiita, we care about the dict, which we will use to display results, but ignore the biom ...

**Comment by wasade** [comment]
See [here](https://github.com/biocore/redbiom/blob/master/redbiom/fetch.py#L311-L313)
