### ISSUE TITLE
create a command to generate figure 2A of MS

### ISSUE THREAD

**Issue by antgonza** [biocore/redbiom#75]
The current MS draft pulls and summarizes results using a sh file;  it will be great if it was possible to do all these in a single biocore command: `redbiom pipeline input-file output-file` -- note that I'm using `pipeline` as I couldn't think of any better name ...

**Comment by wasade** [comment]
I think in practice this need hasn't come up, so I'm going to close it out on that basis but please reopen if this is a priority
