### ISSUE TITLE
All public samples not being searched?

### ISSUE THREAD

**Issue by adswafford** [biocore/redbiom#77]
Study 11713 is public but no samples are returned:
https://qiita.ucsd.edu/study/description/11713#

redbiom search metadata "where qiita_study_id=='11713'" | redbiom summarize samples --category qiita_study_id

Total samples   0

Positive control:
redbiom search metadata "where qiita_study_id=='10317'" | redbiom summarize samples --category qiita_study_id
10317   24897

Total samples   24897

**Comment by antgonza** [comment]
My _guess_ is that study 11713 became public after the last release AKA the solution is: https://github.com/biocore/qiita/issues/2773

**Comment by adswafford** [comment]
Gotcha, no resolution then except to wait for the next redbiom update?

**Comment by antgonza** [comment]
Right ...

**Comment by wasade** [comment]
The loading mechanism from Qiita is to be part of Qiita, closing as such.
